/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as H5RouteImport } from './routes/h5'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAuthRouteImport } from './routes/admin/_auth'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AdminAuthVisitorsIndexRouteImport } from './routes/admin/_auth/visitors/index'
import { Route as AdminAuthUsersIndexRouteImport } from './routes/admin/_auth/users/index'
import { Route as AdminAuthTemplatesIndexRouteImport } from './routes/admin/_auth/templates/index'
import { Route as AdminAuthMappingsIndexRouteImport } from './routes/admin/_auth/mappings/index'
import { Route as AdminAuthDictionaryIndexRouteImport } from './routes/admin/_auth/dictionary/index'
import { Route as AdminAuthDashboardIndexRouteImport } from './routes/admin/_auth/dashboard/index'
import { Route as AdminAuthBlacklistIndexRouteImport } from './routes/admin/_auth/blacklist/index'
import { Route as AdminAuthAuditLogsIndexRouteImport } from './routes/admin/_auth/audit-logs/index'
import { Route as AdminAuth403IndexRouteImport } from './routes/admin/_auth/403/index'

const H5Route = H5RouteImport.update({
  id: '/h5',
  path: '/h5',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthVisitorsIndexRoute = AdminAuthVisitorsIndexRouteImport.update({
  id: '/visitors/',
  path: '/visitors/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthUsersIndexRoute = AdminAuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthTemplatesIndexRoute = AdminAuthTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthMappingsIndexRoute = AdminAuthMappingsIndexRouteImport.update({
  id: '/mappings/',
  path: '/mappings/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthDictionaryIndexRoute =
  AdminAuthDictionaryIndexRouteImport.update({
    id: '/dictionary/',
    path: '/dictionary/',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthDashboardIndexRoute = AdminAuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthBlacklistIndexRoute = AdminAuthBlacklistIndexRouteImport.update({
  id: '/blacklist/',
  path: '/blacklist/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthAuditLogsIndexRoute = AdminAuthAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuth403IndexRoute = AdminAuth403IndexRouteImport.update({
  id: '/403/',
  path: '/403/',
  getParentRoute: () => AdminAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/h5': typeof H5Route
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/403/': typeof AdminAuth403IndexRoute
  '/admin/audit-logs/': typeof AdminAuthAuditLogsIndexRoute
  '/admin/blacklist/': typeof AdminAuthBlacklistIndexRoute
  '/admin/dashboard/': typeof AdminAuthDashboardIndexRoute
  '/admin/dictionary/': typeof AdminAuthDictionaryIndexRoute
  '/admin/mappings/': typeof AdminAuthMappingsIndexRoute
  '/admin/templates/': typeof AdminAuthTemplatesIndexRoute
  '/admin/users/': typeof AdminAuthUsersIndexRoute
  '/admin/visitors/': typeof AdminAuthVisitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/h5': typeof H5Route
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/403': typeof AdminAuth403IndexRoute
  '/admin/audit-logs': typeof AdminAuthAuditLogsIndexRoute
  '/admin/blacklist': typeof AdminAuthBlacklistIndexRoute
  '/admin/dashboard': typeof AdminAuthDashboardIndexRoute
  '/admin/dictionary': typeof AdminAuthDictionaryIndexRoute
  '/admin/mappings': typeof AdminAuthMappingsIndexRoute
  '/admin/templates': typeof AdminAuthTemplatesIndexRoute
  '/admin/users': typeof AdminAuthUsersIndexRoute
  '/admin/visitors': typeof AdminAuthVisitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/h5': typeof H5Route
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/_auth/403/': typeof AdminAuth403IndexRoute
  '/admin/_auth/audit-logs/': typeof AdminAuthAuditLogsIndexRoute
  '/admin/_auth/blacklist/': typeof AdminAuthBlacklistIndexRoute
  '/admin/_auth/dashboard/': typeof AdminAuthDashboardIndexRoute
  '/admin/_auth/dictionary/': typeof AdminAuthDictionaryIndexRoute
  '/admin/_auth/mappings/': typeof AdminAuthMappingsIndexRoute
  '/admin/_auth/templates/': typeof AdminAuthTemplatesIndexRoute
  '/admin/_auth/users/': typeof AdminAuthUsersIndexRoute
  '/admin/_auth/visitors/': typeof AdminAuthVisitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/h5'
    | '/admin/login/'
    | '/admin/403/'
    | '/admin/audit-logs/'
    | '/admin/blacklist/'
    | '/admin/dashboard/'
    | '/admin/dictionary/'
    | '/admin/mappings/'
    | '/admin/templates/'
    | '/admin/users/'
    | '/admin/visitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/h5'
    | '/admin/login'
    | '/admin/403'
    | '/admin/audit-logs'
    | '/admin/blacklist'
    | '/admin/dashboard'
    | '/admin/dictionary'
    | '/admin/mappings'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/visitors'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/h5'
    | '/admin/_auth'
    | '/admin/login/'
    | '/admin/_auth/403/'
    | '/admin/_auth/audit-logs/'
    | '/admin/_auth/blacklist/'
    | '/admin/_auth/dashboard/'
    | '/admin/_auth/dictionary/'
    | '/admin/_auth/mappings/'
    | '/admin/_auth/templates/'
    | '/admin/_auth/users/'
    | '/admin/_auth/visitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  H5Route: typeof H5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/h5': {
      id: '/h5'
      path: '/h5'
      fullPath: '/h5'
      preLoaderRoute: typeof H5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_auth/visitors/': {
      id: '/admin/_auth/visitors/'
      path: '/visitors'
      fullPath: '/admin/visitors/'
      preLoaderRoute: typeof AdminAuthVisitorsIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/users/': {
      id: '/admin/_auth/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAuthUsersIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/templates/': {
      id: '/admin/_auth/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminAuthTemplatesIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/mappings/': {
      id: '/admin/_auth/mappings/'
      path: '/mappings'
      fullPath: '/admin/mappings/'
      preLoaderRoute: typeof AdminAuthMappingsIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dictionary/': {
      id: '/admin/_auth/dictionary/'
      path: '/dictionary'
      fullPath: '/admin/dictionary/'
      preLoaderRoute: typeof AdminAuthDictionaryIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard/': {
      id: '/admin/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminAuthDashboardIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/blacklist/': {
      id: '/admin/_auth/blacklist/'
      path: '/blacklist'
      fullPath: '/admin/blacklist/'
      preLoaderRoute: typeof AdminAuthBlacklistIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/audit-logs/': {
      id: '/admin/_auth/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AdminAuthAuditLogsIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/403/': {
      id: '/admin/_auth/403/'
      path: '/403'
      fullPath: '/admin/403/'
      preLoaderRoute: typeof AdminAuth403IndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuth403IndexRoute: typeof AdminAuth403IndexRoute
  AdminAuthAuditLogsIndexRoute: typeof AdminAuthAuditLogsIndexRoute
  AdminAuthBlacklistIndexRoute: typeof AdminAuthBlacklistIndexRoute
  AdminAuthDashboardIndexRoute: typeof AdminAuthDashboardIndexRoute
  AdminAuthDictionaryIndexRoute: typeof AdminAuthDictionaryIndexRoute
  AdminAuthMappingsIndexRoute: typeof AdminAuthMappingsIndexRoute
  AdminAuthTemplatesIndexRoute: typeof AdminAuthTemplatesIndexRoute
  AdminAuthUsersIndexRoute: typeof AdminAuthUsersIndexRoute
  AdminAuthVisitorsIndexRoute: typeof AdminAuthVisitorsIndexRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuth403IndexRoute: AdminAuth403IndexRoute,
  AdminAuthAuditLogsIndexRoute: AdminAuthAuditLogsIndexRoute,
  AdminAuthBlacklistIndexRoute: AdminAuthBlacklistIndexRoute,
  AdminAuthDashboardIndexRoute: AdminAuthDashboardIndexRoute,
  AdminAuthDictionaryIndexRoute: AdminAuthDictionaryIndexRoute,
  AdminAuthMappingsIndexRoute: AdminAuthMappingsIndexRoute,
  AdminAuthTemplatesIndexRoute: AdminAuthTemplatesIndexRoute,
  AdminAuthUsersIndexRoute: AdminAuthUsersIndexRoute,
  AdminAuthVisitorsIndexRoute: AdminAuthVisitorsIndexRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface AdminRouteChildren {
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  H5Route: H5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
